модуляция
htmlacademy-javascript/1812029-keksobooking-23 pull request #5
Opened 2021-06-22 10:07 UTC by Deniss379379

2021-06-22 10:17 UTC, Deniss379379 commented
Добрый день, разбил код на модули следующим образом: main - точка входа и функции в папке  utils. 
Дополнительно изменил функцию по выдаче уникального значения (для формирования строки об авторе) так как, то что я написал в предыдущем домашнем задании оказалось очень магической конструкцией (подробней расскажу на консультации).

2021-06-22 11:34 UTC, Kirr461 requested changes

2021-06-22 11:34 UTC, Kirr461 commented on js/main.js
> +export default 'main.js';
Здесь не надо ничего экспортировать.

2021-06-22 11:34 UTC, Kirr461 commented on js/main.js
>  const maxRange = 10;
Все эти константы нужно в отдельный файл вынести.

2021-06-22 11:34 UTC, Kirr461 commented on js/main.js
>  const getRandomAvatar = () => {
Этот и все методы ниже должны быть в отдельном модуле. Тут остается только импорт одного метода, который генерирует массив с данными и его вызов.

2021-06-22 11:34 UTC, Kirr461 commented on js/main.js
>  const getSimularObjects = (count) => new Array(count).fill().map(() => {
Соответственно как раз вот этот метод должен экспортироваться отдельным модулем, а тут только вызыватся.

2021-06-22 15:12 UTC, Deniss379379 commented on js/main.js
> +export default 'main.js';
убрал

2021-06-22 15:12 UTC, Deniss379379 commented on js/main.js
>  const maxRange = 10;
вынес

2021-06-22 15:12 UTC, Deniss379379 commented on js/main.js
>  const getRandomAvatar = () => {
вынес

2021-06-22 15:13 UTC, Deniss379379 commented on js/main.js
>  const getSimularObjects = (count) => new Array(count).fill().map(() => {
вынес

2021-06-23 11:25 UTC, Kirr461 approved these changes

2021-06-23 15:32 UTC, merged